name: 'Android Tests Reporter'
description: 'Reports Android Tests Results to GitHub Actions Summary'
inputs:
  working-directory:
    description: 'The working directory to run the tests'
    required: false
    default: '.'
  show-skipped:
    description: 'Show skipped tests in the summary'
    required: false
    default: 'false'
  report-header-postfix:
    description: 'The postfix to add to the report header'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.mjs'
branding:
  icon: 'arrow-right-circle'
  color: 'green'
