on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    name: Test Report Action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: ./ # Uses an action in the root directory
        with:
          working-directory: "./test_data"
          show-skipped: "true"
          report-header-postfix: "(OS: ${{ matrix.os }})"
